url: "https://neelyv.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/victorianeely.com" # the subpath of your site, e.g. /blog
title: "Victoria Neely" # the name of your site
email: hello@victorianeely.me
destination: ./docs